"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Check, Edit3, Eraser, RefreshCw, Trash2, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { queueMutation } from "../../lib/offlineQueue";
import { readCache, writeCache } from "../../lib/localCache";

type Venda={id:string;produto:string;quantidade:number;valor:number;data:string;observacao?:string|null;complementos?:string[]|null;estoque_processado?:boolean};
type ReceitaItem={id:string;receita_id:string;insumo_id:string;quantidade:number;produto?:{nome:string;unidade:string;qtd:number}|null};
type Receita={id:string;nome:string;tipo:"produto"|"complemento";preco:number|null;ativo:boolean;itens:ReceitaItem[]};
type Produto={id:string;nome:string;qtd:number;unidade:string};
const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
const num=(n:number)=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(n);
const dayKey=(value:Date|string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value));
const todayKey=()=>dayKey(new Date());
const CACHE="vendas:items",RECIPES_CACHE="vendas:recipes",PRODUCTS_CACHE="vendas:products";

export default function Vendas(){
 const cachedVendas=readCache<Venda[]>(CACHE,[]),cachedReceitas=readCache<Receita[]>(RECIPES_CACHE,[]),cachedProdutos=readCache<Produto[]>(PRODUCTS_CACHE,[]);
 const [vendas,setVendas]=useState<Venda[]>(cachedVendas),[receitas,setReceitas]=useState<Receita[]>(cachedReceitas),[produtos,setProdutos]=useState<Produto[]>(cachedProdutos),[loading,setLoading]=useState(cachedVendas.length===0&&cachedReceitas.length===0),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const [form,setForm]=useState({receitaId:"",quantidade:"1",complementos:[] as string[],valor:"",observacao:""});
 const [editing,setEditing]=useState<string|null>(null),[editForm,setEditForm]=useState({produto:"",quantidade:"",valor:"",observacao:"",complementos:[] as string[]});
 const produtosVenda=useMemo(()=>receitas.filter(r=>r.tipo==="produto"&&r.ativo),[receitas]);
 const complementos=useMemo(()=>receitas.filter(r=>r.tipo==="complemento"&&r.ativo),[receitas]);
 const selectedRecipe=useMemo(()=>produtosVenda.find(r=>r.id===form.receitaId),[produtosVenda,form.receitaId]);
 const selectedPrice=useMemo(()=>Number(selectedRecipe?.preco??0)+(form.complementos.length>3?1:0),[selectedRecipe,form.complementos.length]);

 async function load(silent=true){
  if(!silent)setLoading(true);
  setError(null);
  try{
   const [salesRes,recipesRes,recipeItemsRes,productsRes]=await Promise.all([
    supabase.from("vendas").select("id,produto,quantidade,valor,data,observacao,complementos,estoque_processado").order("data",{ascending:false}).limit(500),
    supabase.from("receitas").select("id,nome,tipo,preco,ativo").order("tipo").order("nome"),
    supabase.from("receita_itens").select("id,receita_id,insumo_id,quantidade,produtos(nome,unidade,qtd)"),
    supabase.from("produtos").select("id,nome,qtd,unidade").order("nome")
   ]);
   const firstError=salesRes.error||recipesRes.error||recipeItemsRes.error||productsRes.error;
   if(firstError)setError(firstError.message);
   if(!salesRes.error){const next=(salesRes.data??[]) as Venda[];setVendas(next);writeCache(CACHE,next)}
   if(!recipesRes.error){const items=(recipeItemsRes.data??[]) as unknown as ReceitaItem[];const next=((recipesRes.data??[]) as Receita[]).map(r=>({...r,itens:items.filter(i=>i.receita_id===r.id)}));setReceitas(next);writeCache(RECIPES_CACHE,next)}
   if(!productsRes.error){const next=(productsRes.data??[]) as Produto[];setProdutos(next);writeCache(PRODUCTS_CACHE,next)}
  }catch(err){setError(err instanceof Error?err.message:"Não foi possível carregar as vendas.")}
  finally{setLoading(false)}
 }
 useEffect(()=>{void load(true)},[]);
 useEffect(()=>{if(!form.receitaId&&produtosVenda[0])setForm(f=>({...f,receitaId:produtosVenda[0].id,valor:String(Number(produtosVenda[0].preco??0))}))},[produtosVenda,form.receitaId]);
 useEffect(()=>{setForm(f=>({...f,valor:selectedPrice?String(selectedPrice*Number(f.quantidade||1)):""}))},[selectedPrice,form.quantidade]);
 function toggleComplement(nome:string){setForm(f=>({...f,complementos:f.complementos.includes(nome)?f.complementos.filter(x=>x!==nome):[...f.complementos,nome]}))}
 function checkStock(recipe:Receita,quantity:number,chosen:string[]){const required=new Map<string,number>();for(const item of recipe.itens)required.set(item.insumo_id,(required.get(item.insumo_id)||0)+Number(item.quantidade)*quantity);for(const name of chosen){const r=complementos.find(x=>x.nome.toLowerCase()===name.toLowerCase());for(const item of r?.itens??[])required.set(item.insumo_id,(required.get(item.insumo_id)||0)+Number(item.quantidade)*quantity)}for(const [id,need] of required){const p=produtos.find(x=>x.id===id);if(p&&Number(p.qtd)+0.0005<need)return `Estoque insuficiente: ${p.nome} precisa de ${num(need)} ${p.unidade}, mas há ${num(Number(p.qtd))}.`}return null}
 async function addSale(e:React.FormEvent){
  e.preventDefault();
  if(saving)return;
  setError(null);
  const quantity=Number(form.quantidade),total=Number(form.valor);
  if(!selectedRecipe||quantity<=0||!Number.isFinite(total)||total<0){setError("Selecione um produto e preencha a quantidade corretamente.");return}
  const stockError=checkStock(selectedRecipe,quantity,form.complementos);if(stockError){setError(stockError);return}
  const payload={id:crypto.randomUUID(),produto:selectedRecipe.nome,quantidade:quantity,valor:total,data:new Date().toISOString(),observacao:form.observacao.trim()||null,complementos:form.complementos,estoque_processado:false};
  setSaving(true);
  try{
   if(typeof navigator!=="undefined"&&!navigator.onLine){queueMutation({table:"vendas",action:"insert",payload});const next=[payload as Venda,...vendas];setVendas(next);writeCache(CACHE,next);setError("Sem conexão. Venda salva localmente e será sincronizada quando a internet voltar.");return}
   const {error:insertError}=await supabase.from("vendas").insert(payload);
   if(insertError){console.error("Erro ao registrar venda:",insertError);setError(`Não foi possível registrar a venda: ${insertError.message}${insertError.hint?` — ${insertError.hint}`:""}`);return}
   const next=[payload as Venda,...vendas];setVendas(next);writeCache(CACHE,next);
   setForm({receitaId:selectedRecipe.id,quantidade:"1",complementos:[],valor:String(Number(selectedRecipe.preco??0)),observacao:""});
  }catch(err){console.error("Erro ao registrar venda:",err);setError(err instanceof Error?`Não foi possível registrar a venda: ${err.message}`:"Não foi possível registrar a venda.")}
  finally{setSaving(false)}
 }
 function startEdit(v:Venda){setEditing(v.id);setEditForm({produto:v.produto,quantidade:String(v.quantidade),valor:String(v.valor),observacao:v.observacao??"",complementos:v.complementos??[]});setError(null)}
 function cancelEdit(){setEditing(null);setEditForm({produto:"",quantidade:"",valor:"",observacao:"",complementos:[]})}
 function saveEdit(id:string){const quantity=Number(editForm.quantidade),total=Number(editForm.valor);if(!editForm.produto.trim()||quantity<=0||total<0){setError("Preencha produto, quantidade e valor corretamente.");return}setError(null);const next={produto:editForm.produto.trim(),quantidade:quantity,valor:total,observacao:editForm.observacao.trim()||null,complementos:editForm.complementos};setVendas(prev=>{const updated=prev.map(v=>v.id===id?{...v,...next}:v);writeCache(CACHE,updated);return updated});cancelEdit();queueMutation({table:"vendas",action:"update",payload:next,match:{column:"id",value:id}})}
 function deleteSale(v:Venda){if(!window.confirm(`Excluir a venda de ${v.quantidade} unidade(s) de ${v.produto}?`))return;setError(null);setVendas(prev=>{const next=prev.filter(x=>x.id!==v.id);writeCache(CACHE,next);return next});queueMutation({table:"vendas",action:"delete",match:{column:"id",value:v.id}})}
 function clearToday(){const today=todayKey(),ids=vendas.filter(v=>dayKey(v.data)===today).map(v=>v.id);if(!ids.length){setError("Não há vendas registradas hoje para limpar.");return}if(!window.confirm(`Isso vai excluir TODAS as ${ids.length} venda(s) de hoje. Continuar?`))return;setError(null);setVendas(prev=>{const next=prev.filter(v=>dayKey(v.data)!==today);writeCache(CACHE,next);return next});ids.forEach(id=>queueMutation({table:"vendas",action:"delete",match:{column:"id",value:id}}))}
 const today=todayKey(),todaySales=useMemo(()=>vendas.filter(v=>dayKey(v.data)===today),[vendas,today]),revenue=useMemo(()=>todaySales.reduce((sum,v)=>sum+Number(v.valor),0),[todaySales]),cups=useMemo(()=>todaySales.reduce((sum,v)=>sum+Number(v.quantidade),0),[todaySales]),ticket=cups?revenue/cups:0;
 return <main className="min-h-screen bg-slate-50 pb-24 sm:pb-0 dark:bg-black"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10"><div className="flex items-center justify-between"><Link href="/" className="text-xs font-medium text-slate-500 hover:text-slate-900">← Início</Link><Link href="/receitas" className="text-xs font-semibold text-slate-900 underline underline-offset-4 dark:text-white">Configurar receitas</Link></div><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-slate-900 dark:text-white">Vendas</h1><p className="mt-1 text-sm text-slate-500">Cada venda agora movimenta o estoque automaticamente pela ficha técnica.</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><button onClick={()=>load(false)} disabled={loading||saving} className="flex items-center justify-center gap-2 rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-black disabled:opacity-60"><RefreshCw size={15} className={loading?"animate-spin":""}/>{loading?"Atualizando...":"Atualizar"}</button><button onClick={clearToday} disabled={loading||saving} className="flex items-center justify-center gap-2 rounded-xl bg-slate-200 px-4 py-3 text-sm font-semibold text-slate-900 dark:bg-white/10 dark:text-white disabled:opacity-60"><Eraser size={15}/>Limpar hoje</button></div></div>{error&&<div className="mt-5 rounded-2xl bg-slate-100 p-4 text-sm text-slate-700 dark:bg-white/10 dark:text-white">{error}</div>}
 <form onSubmit={addSale} className="mt-6 rounded-2xl bg-white p-5 shadow-none dark:bg-[#080808] sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold tracking-[-0.02em] dark:text-white">Registrar venda</h2><p className="mt-1 text-xs text-slate-500">A venda só aparece como registrada depois da confirmação do banco.</p></div><span className="text-lg font-semibold dark:text-white">{money(selectedPrice*Number(form.quantidade||0))}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><select required value={form.receitaId} onChange={e=>setForm({...form,receitaId:e.target.value})} className="border px-3 py-3 text-sm dark:bg-black dark:text-white"><option value="">Produto</option>{produtosVenda.map(r=><option key={r.id} value={r.id}>{r.nome} · {money(Number(r.preco??0))}</option>)}</select><input required type="number" min="1" step="1" value={form.quantidade} onChange={e=>setForm({...form,quantidade:e.target.value})} placeholder="Quantidade" className="border px-3 py-3 text-sm dark:bg-black dark:text-white"/><input required type="number" min="0" step="0.01" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})} placeholder="Valor total (R$)" className="border px-3 py-3 text-sm dark:bg-black dark:text-white"/></div>{complementos.length>0&&<div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Complementos · até 3 grátis</p><div className="mt-2 flex flex-wrap gap-2">{complementos.map(c=><button type="button" key={c.id} onClick={()=>toggleComplement(c.nome)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${form.complementos.includes(c.nome)?"bg-black text-white dark:bg-white dark:text-black":"border-slate-200 text-slate-600 dark:border-white/10 dark:text-slate-300"}`}>{form.complementos.includes(c.nome)?"✓ ":""}{c.nome}</button>)}</div></div>}<input value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})} placeholder="Observação (opcional)" className="mt-3 w-full border px-3 py-3 text-sm dark:bg-black dark:text-white"/><button disabled={saving||loading} className="mt-3 w-full rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-black disabled:opacity-60">{saving?"Registrando...":"Registrar venda"}</button></form>
 <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white p-4 dark:bg-[#080808]"><p className="text-xs font-medium text-slate-500">Hoje</p><b className="mt-2 block text-xl tracking-[-0.03em] dark:text-white">{loading?"...":money(revenue)}</b></div><div className="rounded-2xl bg-white p-4 dark:bg-[#080808]"><p className="text-xs font-medium text-slate-500">Copos hoje</p><b className="mt-2 block text-xl tracking-[-0.03em] dark:text-white">{loading?"...":cups}</b></div><div className="col-span-2 rounded-2xl bg-white p-4 dark:bg-[#080808] sm:col-span-1"><p className="text-xs font-medium text-slate-500">Ticket médio</p><b className="mt-2 block text-xl tracking-[-0.03em] dark:text-white">{loading?"...":money(ticket)}</b></div></div>
 <section className="mt-5 rounded-2xl bg-white shadow-none dark:bg-[#080808] sm:mt-6"><div className="hidden grid-cols-[1fr_1.2fr_.6fr_1fr_auto] gap-2 px-5 py-4 text-[11px] font-semibold uppercase tracking-wide text-slate-400 sm:grid"><span>Data</span><span>Produto</span><span>Qtd.</span><span>Faturamento</span><span>Ações</span></div>{loading?<div className="p-8 text-center text-sm text-slate-500">Carregando...</div>:vendas.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhuma venda registrada.</div>:<div className="divide-y divide-slate-100 dark:divide-white/10">{vendas.map(v=>editing===v.id?<div key={v.id} className="bg-slate-50 px-5 py-5 dark:bg-white/[.04]"><div className="grid gap-3 sm:grid-cols-4"><input value={editForm.produto} onChange={e=>setEditForm({...editForm,produto:e.target.value})} className="border px-3 py-3 text-sm dark:bg-black dark:text-white" placeholder="Produto"/><input type="number" min="1" value={editForm.quantidade} onChange={e=>setEditForm({...editForm,quantidade:e.target.value})} className="border px-3 py-3 text-sm dark:bg-black dark:text-white" placeholder="Quantidade"/><input type="number" min="0" step="0.01" value={editForm.valor} onChange={e=>setEditForm({...editForm,valor:e.target.value})} className="border px-3 py-3 text-sm dark:bg-black dark:text-white" placeholder="Valor"/><input value={editForm.observacao} onChange={e=>setEditForm({...editForm,observacao:e.target.value})} className="border px-3 py-3 text-sm dark:bg-black dark:text-white" placeholder="Observação"/></div><div className="mt-3 flex gap-2"><button onClick={()=>saveEdit(v.id)} className="flex items-center gap-2 rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white dark:bg-white dark:text-black"><Check size={14}/>Salvar</button><button onClick={cancelEdit} className="flex items-center gap-2 rounded-xl bg-slate-200 px-4 py-2 text-xs font-semibold"><X size={14}/>Cancelar</button></div></div>:<div key={v.id} className="grid gap-3 px-5 py-5 sm:grid-cols-[1fr_1.2fr_.6fr_1fr_auto] sm:items-center"><div className="text-xs text-slate-500">{new Date(v.data).toLocaleString("pt-BR")}</div><div className="font-semibold dark:text-white">{v.produto}</div><div className="text-sm dark:text-white">{v.quantidade}</div><div className="text-sm font-semibold dark:text-white">{money(Number(v.valor))}</div><div className="flex gap-2"><button onClick={()=>startEdit(v)} className="rounded-lg bg-slate-100 p-2 dark:bg-white/10 dark:text-white" aria-label="Editar"><Edit3 size={15}/></button><button onClick={()=>deleteSale(v)} className="rounded-lg bg-slate-100 p-2 dark:bg-white/10 dark:text-white" aria-label="Excluir"><Trash2 size={15}/></button></div></div>)}</div>}</section></div></main>;
}