"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "../../lib/supabase";

type Config={id:string;user_name:string|null;negocio:string|null;margem:number|null;preco_copo:number|null;meta_diaria:number|null;updated_at:string};
export default function Parametros(){
 const [config,setConfig]=useState<Config|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const [form,setForm]=useState({user_name:"",negocio:"",margem:"",preco_copo:"",meta_diaria:""});
 async function load(){setLoading(true);setError(null);const {data,error}=await supabase.from("config").select("id,user_name,negocio,margem,preco_copo,meta_diaria,updated_at").limit(1).maybeSingle();if(error)setError(error.message);else if(data){setConfig(data as Config);setForm({user_name:data.user_name??"",negocio:data.negocio??"",margem:data.margem==null?"":String(data.margem),preco_copo:data.preco_copo==null?"":String(data.preco_copo),meta_diaria:data.meta_diaria==null?"":String(data.meta_diaria)})}else setConfig(null);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError(null);const margem=form.margem===""?null:Number(form.margem),preco=form.preco_copo===""?null:Number(form.preco_copo),meta=form.meta_diaria===""?null:Number(form.meta_diaria);if([margem,preco,meta].some(v=>v!==null&&!Number.isFinite(v))){setError("Valores numéricos inválidos.");setSaving(false);return}const payload={user_name:form.user_name.trim()||null,negocio:form.negocio.trim()||null,margem,preco_copo:preco,meta_diaria:meta,updated_at:new Date().toISOString()};const result=config?await supabase.from("config").update(payload).eq("id",config.id):await supabase.from("config").insert(payload);if(result.error)setError(result.error.message);else await load();setSaving(false)}
 async function logout(){await supabase.auth.signOut();}
 return <main className="min-h-screen bg-slate-50 pb-24 sm:pb-0"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-8"><Link href="/" className="text-sm text-acai-700 hover:underline">← Início</Link><div className="mt-3 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold sm:text-3xl">Parâmetros</h1><p className="mt-1 text-sm text-slate-500">Configurações da sua conta, salvas no Supabase.</p></div><button type="button" onClick={logout} className="rounded-xl border px-4 py-2 text-sm font-semibold">Sair</button></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<form onSubmit={save} className="mt-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Nome<input value={form.user_name} onChange={e=>setForm({...form,user_name:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3" placeholder="Seu nome"/></label><label className="text-sm">Negócio<input value={form.negocio} onChange={e=>setForm({...form,negocio:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3" placeholder="Nome do negócio"/></label><label className="text-sm">Margem (%)<input type="number" value={form.margem} onChange={e=>setForm({...form,margem:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm">Preço padrão do copo (R$)<input type="number" step="0.01" value={form.preco_copo} onChange={e=>setForm({...form,preco_copo:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3"/></label><label className="text-sm">Meta diária (copos)<input type="number" min="0" value={form.meta_diaria} onChange={e=>setForm({...form,meta_diaria:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3"/></label></div><button disabled={saving} className="mt-5 w-full rounded-xl bg-acai-700 px-4 py-3 font-semibold text-white sm:w-auto">{saving?"Salvando...":"Salvar configurações"}</button></form><div className="mt-4 rounded-2xl border bg-white p-4 text-sm text-slate-600 shadow-sm">{loading?"Carregando...":config?`Preço padrão: R$ ${Number(config.preco_copo??0).toFixed(2).replace(".",",")} · Meta: ${config.meta_diaria??0} copos`:`Nenhuma configuração cadastrada.`}</div></div></main>;
}