"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import MobileNav from "../components/MobileNav";
import { supabase } from "../../lib/supabase";
import { queueMutation } from "../../lib/offlineQueue";
import { readCache, writeCache } from "../../lib/localCache";

type Produto={id:string;nome:string;qtd:number;custo:number;min:number;unidade:string;updated_at:string};
const num=(n:number)=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(n);
const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
const qty=(n:number,u:string)=>`${num(n)} ${u==="litros"?"L":u}`;
const CACHE="estoque:produtos";

export default function Estoque(){
 const cached=readCache<Produto[]>(CACHE,[]);
 const [items,setItems]=useState<Produto[]>(cached),[loading,setLoading]=useState(cached.length===0),[error,setError]=useState<string|null>(null);
 const [form,setForm]=useState({nome:"",qtd:"",custo:"",min:"",unidade:"un"});
 async function load(silent=true){if(!silent)setLoading(true);setError(null);const {data,error}=await supabase.from("produtos").select("id,nome,qtd,custo,min,unidade,updated_at").order("nome");if(error){setError(error.message)}else{const next=(data??[])as Produto[];setItems(next);writeCache(CACHE,next)}if(!silent)setLoading(false)}
 useEffect(()=>{void load(true)},[]);
 function add(e:React.FormEvent){e.preventDefault();setError(null);const qtd=Number(form.qtd),custo=Number(form.custo),min=Number(form.min);if(!form.nome.trim()||!Number.isFinite(qtd)||qtd<0||!Number.isFinite(custo)||custo<0||!Number.isFinite(min)||min<0){setError("Preencha os campos corretamente.");return}const payload={id:crypto.randomUUID(),nome:form.nome.trim(),qtd,custo,min,unidade:form.unidade.trim()||"un",updated_at:new Date().toISOString()};setItems(prev=>{const next=[payload as Produto,...prev].sort((a,b)=>a.nome.localeCompare(b.nome));writeCache(CACHE,next);return next});setForm({nome:"",qtd:"",custo:"",min:"",unidade:"un"});queueMutation({table:"produtos",action:"insert",payload});}
 function edit(p:Produto){const raw=window.prompt(`Nova quantidade para ${p.nome}`,String(p.qtd));if(raw===null)return;const qtd=Number(raw);if(!Number.isFinite(qtd)||qtd<0){setError("Quantidade inválida.");return}setError(null);const updated_at=new Date().toISOString();setItems(prev=>{const next=prev.map(x=>x.id===p.id?{...x,qtd,updated_at}:x);writeCache(CACHE,next);return next});queueMutation({table:"produtos",action:"update",payload:{qtd,updated_at},match:{column:"id",value:p.id}})}
 function remove(p:Produto){if(!window.confirm(`Excluir ${p.nome}?`))return;setError(null);setItems(prev=>{const next=prev.filter(x=>x.id!==p.id);writeCache(CACHE,next);return next});queueMutation({table:"produtos",action:"delete",match:{column:"id",value:p.id}})}
 const total=useMemo(()=>items.reduce((s,p)=>s+Number(p.qtd)*Number(p.custo),0),[items]);const low=items.filter(p=>Number(p.qtd)<=Number(p.min)).length;const acai=items.find(p=>p.nome.toLowerCase()==="açaí");
 return <main className="min-h-screen bg-slate-50 pb-24 sm:pb-0"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-8 sm:py-10"><Link href="/" className="text-xs font-medium text-slate-500 hover:text-slate-900">← Início</Link><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-0.04em] text-slate-900">Estoque</h1><p className="mt-1 text-sm text-slate-500">Produtos, quantidades e custos.</p></div><button onClick={()=>load(false)} disabled={loading} className="w-full rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-black sm:w-auto">{loading?"Atualizando...":"Atualizar"}</button></div>{error&&<div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <form onSubmit={add} className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-semibold tracking-[-0.02em]">Adicionar produto</h2><div className="mt-4 grid gap-3 sm:grid-cols-5"><input required value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} placeholder="Nome" className="border px-3 py-3 text-sm"/><input required type="number" min="0" step="0.01" value={form.qtd} onChange={e=>setForm({...form,qtd:e.target.value})} placeholder="Quantidade" className="border px-3 py-3 text-sm"/><input required type="number" min="0" step="0.01" value={form.custo} onChange={e=>setForm({...form,custo:e.target.value})} placeholder="Custo unitário" className="border px-3 py-3 text-sm"/><input required type="number" min="0" value={form.min} onChange={e=>setForm({...form,min:e.target.value})} placeholder="Mínimo" className="border px-3 py-3 text-sm"/><button className="rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white dark:bg-white dark:text-black">Adicionar</button></div><input value={form.unidade} onChange={e=>setForm({...form,unidade:e.target.value})} placeholder="Unidade: un, L, kg..." className="mt-3 w-full border px-3 py-3 text-sm"/></form>
 <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium text-slate-500">Açaí</p><b className="mt-2 block text-xl tracking-[-0.03em]">{loading?"...":acai?qty(Number(acai.qtd),acai.unidade):"0 L"}</b></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium text-slate-500">Valor do estoque</p><b className="mt-2 block text-xl tracking-[-0.03em]">{loading?"...":money(total)}</b></div><div className="col-span-2 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:col-span-1"><p className="text-xs font-medium text-slate-500">Para revisar</p><b className="mt-2 block text-xl tracking-[-0.03em]">{loading?"...":low}</b></div></div>
 <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm sm:mt-6"><div className="border-b border-slate-200 px-5 py-4 font-semibold">Produtos</div>{loading?<div className="p-8 text-center text-sm text-slate-500">Carregando...</div>:items.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhum produto cadastrado.</div>:items.map(p=><div key={p.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-slate-200 px-5 py-4 last:border-0 sm:grid-cols-[1fr_auto_auto_auto]"><div><b className="font-semibold">{p.nome}</b><p className="mt-1 text-xs text-slate-400">Mínimo: {qty(Number(p.min),p.unidade)} · Custo: {money(Number(p.custo))}</p></div><span className="text-right text-sm font-medium">{qty(Number(p.qtd),p.unidade)}</span><button onClick={()=>edit(p)} className="rounded-lg border border-slate-200 px-3 py-1 text-xs font-medium">Editar</button><button onClick={()=>remove(p)} className="rounded-lg border border-slate-200 px-3 py-1 text-xs font-medium text-red-600">Excluir</button></div>)}</section></div><MobileNav/></main>;
}