"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import MobileNav from "../components/MobileNav";
import { supabase } from "../../lib/supabase";

type Clima={id:string;data:string;temperatura:number|null;condicao:string|null;umidade:number|null;observacao:string|null};
export default function Clima(){
 const [items,setItems]=useState<Clima[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);const {data,error}=await supabase.from("clima").select("id,data,temperatura,condicao,umidade,observacao").order("data",{ascending:false}).limit(30);if(error)setError(error.message);else setItems((data??[])as Clima[]);setLoading(false)}
 useEffect(()=>{load()},[]);const today=new Date().toISOString().slice(0,10),current=items.find(x=>x.data===today)||items[0];
 return <main className="min-h-screen bg-slate-50 pb-24 sm:pb-0"><div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-8"><Link href="/" className="text-sm text-acai-700 hover:underline">← Início</Link><div className="mt-3 flex items-end justify-between gap-3"><div><h1 className="text-2xl font-bold sm:text-3xl">Clima</h1><p className="mt-1 text-sm text-slate-500">Registros reais da tabela clima.</p></div><button onClick={load} disabled={loading} className="rounded-xl bg-acai-700 px-4 py-3 text-sm font-semibold text-white">{loading?"...":"↻ Atualizar"}</button></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<section className="mt-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-6">{loading?<p>Carregando...</p>:!current?<div className="py-8 text-center text-sm text-slate-500">Nenhum registro de clima.</div>:<><p className="text-sm text-slate-500">Registro mais recente</p><h2 className="mt-1 text-xl font-bold sm:text-2xl">{current.temperatura==null?"--":`${current.temperatura}°C`} · {current.condicao||"Sem condição informada"}</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Data</p><b>{new Date(current.data+"T12:00:00").toLocaleDateString("pt-BR")}</b></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Umidade</p><b>{current.umidade==null?"--":`${current.umidade}%`}</b></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Observação</p><b>{current.observacao||"--"}</b></div></div></>}</section><section className="mt-4 overflow-hidden rounded-2xl border bg-white shadow-sm sm:mt-6"><div className="border-b px-4 py-4 font-semibold">Histórico</div>{loading?<div className="p-8 text-center text-sm text-slate-500">Carregando...</div>:items.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhum registro.</div>:items.map(i=><div key={i.id} className="flex justify-between gap-4 border-b px-4 py-4 text-sm last:border-0"><span>{new Date(i.data+"T12:00:00").toLocaleDateString("pt-BR")} · {i.condicao||"Sem condição"}</span><b>{i.temperatura==null?"--":`${i.temperatura}°C`}</b></div>)}</section></div><MobileNav/></main>;
}