"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import MobileNav from "../components/MobileNav";
import { supabase } from "../../lib/supabase";

type Gasto={id:string;nome:string;valor:number;tipo:string;data:string;observacao?:string|null};
const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
export default function Gastos(){
 const [gastos,setGastos]=useState<Gasto[]>([]),[vendas,setVendas]=useState<number[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const [form,setForm]=useState({nome:"",valor:"",tipo:"Operacional",data:new Date().toISOString().slice(0,10),observacao:""});
 async function load(){setLoading(true);setError(null);const [g,s]=await Promise.all([supabase.from("gastos").select("id,nome,valor,tipo,data,observacao").order("data",{ascending:false}).limit(100),supabase.from("vendas").select("valor").limit(500)]);if(g.error||s.error)setError(g.error?.message||s.error?.message||"Erro ao carregar dados");setGastos((g.data??[])as Gasto[]);setVendas((s.data??[]).map(x=>Number(x.valor)));setLoading(false)}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);setError(null);const valor=Number(form.valor);if(!form.nome.trim()||!Number.isFinite(valor)||valor<=0||!form.data){setError("Preencha descrição, valor e data corretamente.");setSaving(false);return}const {error}=await supabase.from("gastos").insert({nome:form.nome.trim(),valor,tipo:form.tipo.trim()||"Operacional",data:form.data,observacao:form.observacao.trim()||null});if(error)setError(error.message);else{setForm({nome:"",valor:"",tipo:"Operacional",data:new Date().toISOString().slice(0,10),observacao:""});await load()}setSaving(false)}
 const total=useMemo(()=>gastos.reduce((s,g)=>s+Number(g.valor),0),[gastos]),revenue=useMemo(()=>vendas.reduce((s,v)=>s+v,0),[vendas]);
 return <main className="min-h-screen bg-slate-50 pb-24 sm:pb-0"><div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 sm:py-8"><Link href="/" className="text-sm text-acai-700 hover:underline">← Início</Link><div className="mt-3"><h1 className="text-2xl font-bold sm:text-3xl">Gastos</h1><p className="mt-1 text-sm text-slate-500">Lançamentos persistidos no Supabase.</p></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <form onSubmit={add} className="mt-5 rounded-2xl border bg-white p-4 shadow-sm sm:p-5"><h2 className="font-semibold">Adicionar gasto</h2><div className="mt-4 grid gap-3 sm:grid-cols-4"><input required value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} placeholder="Descrição" className="rounded-xl border px-3 py-3 text-sm"/><input required type="number" min="0.01" step="0.01" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})} placeholder="Valor (R$)" className="rounded-xl border px-3 py-3 text-sm"/><input required value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} placeholder="Tipo" className="rounded-xl border px-3 py-3 text-sm"/><button disabled={saving} className="rounded-xl bg-acai-700 px-4 py-3 font-semibold text-white">{saving?"Salvando...":"Adicionar"}</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input required type="date" value={form.data} onChange={e=>setForm({...form,data:e.target.value})} className="rounded-xl border px-3 py-3 text-sm"/><input value={form.observacao} onChange={e=>setForm({...form,observacao:e.target.value})} placeholder="Observação (opcional)" className="rounded-xl border px-3 py-3 text-sm"/></div></form>
 <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">Gastos</p><b className="mt-2 block text-xl">{loading?"...":money(total)}</b></div><div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">Faturamento</p><b className="mt-2 block text-xl text-emerald-600">{loading?"...":money(revenue)}</b></div><div className="col-span-2 rounded-2xl border bg-white p-4 shadow-sm sm:col-span-1"><p className="text-xs text-slate-500">Saldo operacional</p><b className="mt-2 block text-xl">{loading?"...":money(revenue-total)}</b></div></div>
 <section className="mt-4 overflow-hidden rounded-2xl border bg-white shadow-sm sm:mt-6"><div className="border-b px-4 py-4 font-semibold">Lançamentos</div>{loading?<div className="p-8 text-center text-sm text-slate-500">Carregando...</div>:gastos.length===0?<div className="p-8 text-center text-sm text-slate-500">Nenhum gasto registrado.</div>:gastos.map(g=><div key={g.id} className="grid grid-cols-[80px_1fr_auto] gap-2 border-b px-4 py-4 text-sm last:border-0"><span className="text-slate-400">{new Date(g.data+"T12:00:00").toLocaleDateString("pt-BR")}</span><span><b>{g.nome}</b><small className="block text-slate-400">{g.tipo}</small></span><span className="font-semibold text-red-600">- {money(Number(g.valor))}</span></div>)}</section></div><MobileNav/></main>;
}